/**
 * Russian
 *
 * LCD Menu Messages
 * Please note these are limited to 17 characters!
 *
 */
#ifndef LANGUAGE_RU_H
#define LANGUAGE_RU_H

#define LANGUAGE_RU

#define WELCOME_MSG                         MACHINE_NAME "����������."
#define MSG_SD_INSERTED                     "���������� ������������������"
#define MSG_SD_REMOVED                      "���������� ������������������"
#define MSG_MAIN                            "�������� \003"
#define MSG_AUTOSTART                       "������������������"
#define MSG_DISABLE_STEPPERS                "��������. ������������������"
#define MSG_AUTO_HOME                       "����������������"
#define MSG_SET_HOME_OFFSETS                "Set home offsets"
#define MSG_SET_ORIGIN                      "������������������ ��������"
#define MSG_PREHEAT_PLA                     "�������������������� PLA"
#define MSG_PREHEAT_PLA0                    "�������������������� PLA0"
#define MSG_PREHEAT_PLA1                    "�������������������� PLA1"
#define MSG_PREHEAT_PLA2                    "�������������������� PLA2"
#define MSG_PREHEAT_PLA012                  "��������������. PLA ������"
#define MSG_PREHEAT_PLA_BEDONLY             "��������. PLA ��������������"
#define MSG_PREHEAT_PLA_SETTINGS            "������������������ PLA"
#define MSG_PREHEAT_ABS                     "�������������������� ABS"
#define MSG_PREHEAT_ABS0                    "�������������������� ABS0"
#define MSG_PREHEAT_ABS1                    "�������������������� ABS1"
#define MSG_PREHEAT_ABS2                    "�������������������� ABS2"
#define MSG_PREHEAT_ABS012                  "��������������. ABS ������ "
#define MSG_PREHEAT_ABS_BEDONLY             "��������. ABS ��������������"
#define MSG_PREHEAT_ABS_SETTINGS            "������������������ ABS"
#define MSG_COOLDOWN                        "��������������������"
#define MSG_SWITCH_PS_ON                    "Switch Power On"
#define MSG_SWITCH_PS_OFF                   "Switch Power Off"
#define MSG_EXTRUDE                         "������������������"
#define MSG_RETRACT                         "����������"
#define MSG_MOVE_AXIS                       "���������������� ���� ��������"
#define MSG_MOVE_X                          "Move X"
#define MSG_MOVE_Y                          "Move Y"
#define MSG_MOVE_Z                          "Move Z"
#define MSG_MOVE_E                          "Extruder"
#define MSG_MOVE_E1                         "Extruder2"
#define MSG_MOVE_E2                         "Extruder3"
#define MSG_MOVE_01MM                       "Move 0.1mm"
#define MSG_MOVE_1MM                        "Move 1mm"
#define MSG_MOVE_10MM                       "Move 10mm"
#define MSG_SPEED                           "����������������:"
#define MSG_NOZZLE                          "\002 ��������������:"
#define MSG_NOZZLE1                         "\002 ��������������2:"
#define MSG_NOZZLE2                         "\002 ��������������3:"
#define MSG_BED                             "\002 ��������������:"
#define MSG_FAN_SPEED                       "������������:"
#define MSG_FLOW                            "����������:"
#define MSG_FLOW0                           " ����������0:"
#define MSG_FLOW1                           " ����������1:"
#define MSG_FLOW2                           " ����������2:"
#define MSG_CONTROL                         "������������������ \003"
#define MSG_MIN                             "\002 ��������������:"
#define MSG_MAX                             "\002 ����������������:"
#define MSG_FACTOR                          "\002 ������������:"
#define MSG_AUTOTEMP                        "Autotemp:"
#define MSG_ON                              "������. "
#define MSG_OFF                             "��������. "
#define MSG_PID_P                           "PID-P: "
#define MSG_PID_I                           "PID-I: "
#define MSG_PID_D                           "PID-D: "
#define MSG_PID_C                           "PID-C: "
#define MSG_ACC                             "Acc:"
#define MSG_VXY_JERK                        "Vxy-jerk: "
#define MSG_VZ_JERK                         "Vz-jerk"
#define MSG_VE_JERK                         "Ve-jerk"
#define MSG_VMAX                            "Vmax "
#define MSG_X                               "x:"
#define MSG_Y                               "y:"
#define MSG_Z                               "z:"
#define MSG_E                               "e:"
#define MSG_VMIN                            "Vmin:"
#define MSG_VTRAV_MIN                       "VTrav min:"
#define MSG_AMAX                            "Amax "
#define MSG_A_RETRACT                       "A-retract:"
#define MSG_XSTEPS                          "X ������/mm:"
#define MSG_YSTEPS                          "Y ������/mm:"
#define MSG_ZSTEPS                          "Z ������/mm:"
#define MSG_ESTEPS                          "E ������/mm:"
#define MSG_TEMPERATURE                     "����������������������     \x7E"
#define MSG_MOTION                          "����������������        \x7E"
#define MSG_VOLUMETRIC                      "Filament"
#define MSG_VOLUMETRIC_ENABLED		        "E in mm3"
#define MSG_FILAMENT_SIZE_EXTRUDER_0        "Fil. Dia. 1"
#define MSG_FILAMENT_SIZE_EXTRUDER_1        "Fil. Dia. 2"
#define MSG_FILAMENT_SIZE_EXTRUDER_2        "Fil. Dia. 3"
#define MSG_CONTRAST                        "LCD contrast"
#define MSG_STORE_EPROM                     "������������������ �� EPROM"
#define MSG_LOAD_EPROM                      "������������. ���� EPROM"
#define MSG_RESTORE_FAILSAFE                "���������� ����������������"
#define MSG_REFRESH                         "\004����������������"
#define MSG_WATCH                           "����������           \003"
#define MSG_PREPARE                         "����������������        \x7E"
#define MSG_TUNE                            "������������������       \x7E"
#define MSG_PAUSE_PRINT                     "�������������������� ������������"
#define MSG_RESUME_PRINT                    "������������. ������������"
#define MSG_STOP_PRINT                      "�������������������� ������������"
#define MSG_CARD_MENU                       "�������� ����������      \x7E"
#define MSG_NO_CARD                         "������ ����������"
#define MSG_DWELL                           "������..."
#define MSG_USERWAIT                        "������������������"
#define MSG_RESUMING                        "Resuming print"
#define MSG_PRINT_ABORTED                   "Print aborted"
#define MSG_NO_MOVE                         "������ ����������������."
#define MSG_KILLED                          "����������."
#define MSG_STOPPED                         "����������������������."
#define MSG_CONTROL_RETRACT                 "���������� mm:"
#define MSG_CONTROL_RETRACT_SWAP            "�������� ���������� mm:"
#define MSG_CONTROL_RETRACTF                "����������  V:"
#define MSG_CONTROL_RETRACT_ZLIFT           "������������ mm:"
#define MSG_CONTROL_RETRACT_RECOVER         "�������������� +mm:"
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    "�������� �������������� +mm:"
#define MSG_CONTROL_RETRACT_RECOVERF        "��������������  V:"
#define MSG_AUTORETRACT                     "������������������:"
#define MSG_FILAMENTCHANGE                  "Change filament"
#define MSG_INIT_SDCARD                     "Init. SD-Card"
#define MSG_CNG_SDCARD                      "Change SD-Card"
#define MSG_ZPROBE_OUT                      "Z probe out. bed"
#define MSG_POSITION_UNKNOWN                "Home X/Y before Z"
#define MSG_ZPROBE_ZOFFSET                  "Z Offset"
#define MSG_BABYSTEP_X                      "Babystep X"
#define MSG_BABYSTEP_Y                      "Babystep Y"
#define MSG_BABYSTEP_Z                      "Babystep Z"
#define MSG_ENDSTOP_ABORT                   "Endstop abort"

#define MSG_RECTRACT                        "���������� ������������    \x7E"

#ifdef DELTA_CALIBRATION_MENU
    #define MSG_DELTA_CALIBRATE             "Delta Calibration"
    #define MSG_DELTA_CALIBRATE_X           "Calibrate X"
    #define MSG_DELTA_CALIBRATE_Y           "Calibrate Y"
    #define MSG_DELTA_CALIBRATE_Z           "Calibrate Z"
    #define MSG_DELTA_CALIBRATE_CENTER      "Calibrate Center"
#endif // DELTA_CALIBRATION_MENU

#endif // LANGUAGE_RU_H

